// `STORY_DATA` を差し替えるだけで、別作品にそのまま転用できます。
// この版では「投稿」のみを使い、各投稿の中に messages を直接並べます。

const STORY_DATA = {
  workId: "urashimataro",
  workTitle: "浦島太郎",
  theme: {
    accentColor: "#79dd67",
    backgroundColor: "#2d2f30"
  },
  posts: [
    {
      postIndex: 1,
      groupName: "浜の騒ぎ",
      participants: ["浦島太郎", "子ども衆", "亀"],
      messages: [
        { type: "system", text: "浦島太郎がグループ「浜の騒ぎ」を作成しました" },
        { type: "system", text: "子ども衆がグループに参加しました" },
        { type: "message", sender: "浦島太郎", text: "浜の方が騒がしいな", isSelf: true, time: "08:14", avatarText: "浦" },
        { type: "message", sender: "子ども衆", text: "見て見て\n亀つかまえた", isSelf: false, time: "08:15", avatarText: "子" },
        { type: "message", sender: "浦島太郎", text: "何してるんだ", isSelf: true, time: "08:15", avatarText: "浦" },
        { type: "message", sender: "子ども衆", text: "遊んでるだけ", isSelf: false, time: "08:15", avatarText: "子" },
        { type: "message", sender: "浦島太郎", text: "亀は全然楽しそうじゃないぞ", isSelf: true, time: "08:16", avatarText: "浦" },
        { type: "message", sender: "子ども衆", text: "ちょっとつついただけ", isSelf: false, time: "08:16", avatarText: "子" },
        { type: "message", sender: "浦島太郎", text: "ちょっとの顔してないだろ", isSelf: true, time: "08:17", avatarText: "浦" },
        { type: "message", sender: "亀", text: "た、助けてください…", isSelf: false, time: "08:17", avatarText: "亀" },
        { type: "message", sender: "浦島太郎", text: "ほら、ちゃんと困ってる", isSelf: true, time: "08:17", avatarText: "浦" },
        { type: "message", sender: "子ども衆", text: "でも珍しいし", isSelf: false, time: "08:18", avatarText: "子" },
        { type: "message", sender: "浦島太郎", text: "珍しいからっていじめていいことにはならん", isSelf: true, time: "08:18", avatarText: "浦" },
        { type: "message", sender: "子ども衆", text: "むう", isSelf: false, time: "08:19", avatarText: "子" },
        { type: "message", sender: "浦島太郎", text: "ほら、もう放してやれ", isSelf: true, time: "08:19", avatarText: "浦" },
        { type: "message", sender: "子ども衆", text: "分かったよ", isSelf: false, time: "08:19", avatarText: "子" },
        { type: "system", text: "子ども衆がグループから退出しました" },
        { type: "message", sender: "亀", text: "助かりました\nご恩は忘れません", isSelf: false, time: "08:22", avatarText: "亀" },
        { type: "message", sender: "浦島太郎", text: "大げさだな\n無事ならそれでいい", isSelf: true, time: "08:22", avatarText: "浦" },
        { type: "message", sender: "亀", text: "いえ、必ずお礼を", isSelf: false, time: "08:23", avatarText: "亀" },
        { type: "message", sender: "浦島太郎", text: "気にするなって", isSelf: true, time: "08:23", avatarText: "浦" },
        { type: "message", sender: "亀", text: "では後日、迎えに参ります", isSelf: false, time: "08:24", avatarText: "亀" },
        { type: "message", sender: "浦島太郎", text: "迎えに？", isSelf: true, time: "08:24", avatarText: "浦" },
        { type: "message", sender: "亀", text: "はい", isSelf: false, time: "08:24", avatarText: "亀" },
        { type: "message", sender: "浦島太郎", text: "どこへ", isSelf: true, time: "08:25", avatarText: "浦" },
        { type: "message", sender: "亀", text: "それは来てからのお楽しみで", isSelf: false, time: "08:25", avatarText: "亀" },
        { type: "message", sender: "浦島太郎", text: "急に含みのある言い方するな", isSelf: true, time: "08:26", avatarText: "浦" }
      ]
    },
    {
      postIndex: 2,
      groupName: "竜宮城への道",
      participants: ["浦島太郎", "亀", "乙姫"],
      messages: [
        { type: "system", text: "亀がグループ「竜宮城への道」に浦島太郎を招待しました" },
        { type: "message", sender: "浦島太郎", text: "ほんとに来たのか", isSelf: true, time: "09:41", avatarText: "浦" },
        { type: "message", sender: "亀", text: "参りました", isSelf: false, time: "09:41", avatarText: "亀" },
        { type: "message", sender: "浦島太郎", text: "迎えにって、まさか本当に迎えに来るとは", isSelf: true, time: "09:42", avatarText: "浦" },
        { type: "message", sender: "亀", text: "お礼をすると申しましたので", isSelf: false, time: "09:42", avatarText: "亀" },
        { type: "message", sender: "浦島太郎", text: "で、どこ行くんだ", isSelf: true, time: "09:43", avatarText: "浦" },
        { type: "message", sender: "亀", text: "竜宮城です", isSelf: false, time: "09:43", avatarText: "亀" },
        { type: "message", sender: "浦島太郎", text: "話が一気に大きくなったな", isSelf: true, time: "09:44", avatarText: "浦" },
        { type: "message", sender: "亀", text: "背中にお乗りください", isSelf: false, time: "09:44", avatarText: "亀" },
        { type: "message", sender: "浦島太郎", text: "乗れるのか", isSelf: true, time: "09:44", avatarText: "浦" },
        { type: "message", sender: "亀", text: "乗れます", isSelf: false, time: "09:45", avatarText: "亀" },
        { type: "message", sender: "浦島太郎", text: "じゃあ失礼する", isSelf: true, time: "09:45", avatarText: "浦" },
        { type: "system", text: "乙姫がグループに参加しました" },
        { type: "message", sender: "乙姫", text: "ようこそ竜宮城へ", isSelf: false, time: "09:47", avatarText: "乙" },
        { type: "message", sender: "浦島太郎", text: "着くの早いな", isSelf: true, time: "09:47", avatarText: "浦" },
        { type: "message", sender: "乙姫", text: "お待ちしておりました", isSelf: false, time: "09:47", avatarText: "乙" },
        { type: "message", sender: "浦島太郎", text: "そんな大げさな", isSelf: true, time: "09:48", avatarText: "浦" },
        { type: "message", sender: "亀", text: "この方が命の恩人です", isSelf: false, time: "09:48", avatarText: "亀" },
        { type: "message", sender: "乙姫", text: "それは丁重にもてなさねばなりません", isSelf: false, time: "09:49", avatarText: "乙" },
        { type: "message", sender: "浦島太郎", text: "なんだか場違いなところに来た気がする", isSelf: true, time: "09:49", avatarText: "浦" },
        { type: "message", sender: "乙姫", text: "今日はゆるりとお過ごしください", isSelf: false, time: "09:50", avatarText: "乙" },
        { type: "message", sender: "浦島太郎", text: "魚が踊ってる", isSelf: true, time: "09:51", avatarText: "浦" },
        { type: "message", sender: "亀", text: "踊っております", isSelf: false, time: "09:51", avatarText: "亀" },
        { type: "message", sender: "浦島太郎", text: "鯛までいる", isSelf: true, time: "09:51", avatarText: "浦" },
        { type: "message", sender: "乙姫", text: "おります", isSelf: false, time: "09:52", avatarText: "乙" },
        { type: "message", sender: "浦島太郎", text: "宴が本気すぎるだろ", isSelf: true, time: "09:52", avatarText: "浦" },
        { type: "message", sender: "乙姫", text: "まだ始まりにすぎません", isSelf: false, time: "09:53", avatarText: "乙" },
        { type: "message", sender: "浦島太郎", text: "これ以上あるのか", isSelf: true, time: "09:53", avatarText: "浦" },
        { type: "message", sender: "亀", text: "ございます", isSelf: false, time: "09:53", avatarText: "亀" },
        { type: "message", sender: "浦島太郎", text: "地上戻れなくなるくらい居心地いいな", isSelf: true, time: "09:54", avatarText: "浦" },
        { type: "message", sender: "乙姫", text: "どうか心ゆくまで", isSelf: false, time: "09:54", avatarText: "乙" }
      ]
    },
    {
      postIndex: 3,
      groupName: "帰る日のこと",
      participants: ["乙姫", "浦島太郎", "亀", "村人"],
      messages: [
        { type: "system", text: "乙姫がグループ「帰る日のこと」を作成しました" },
        { type: "system", text: "浦島太郎がグループに参加しました" },
        { type: "system", text: "亀がグループに参加しました" },
        { type: "message", sender: "乙姫", text: "本当にお帰りになるのですか", isSelf: false, time: "12:06", avatarText: "乙" },
        { type: "message", sender: "浦島太郎", text: "ああ\nそろそろ村のことも気になる", isSelf: true, time: "12:07", avatarText: "浦" },
        { type: "message", sender: "亀", text: "名残惜しゅうございます", isSelf: false, time: "12:07", avatarText: "亀" },
        { type: "message", sender: "乙姫", text: "では、これをお持ちください", isSelf: false, time: "12:08", avatarText: "乙" },
        { type: "message", sender: "浦島太郎", text: "箱？", isSelf: true, time: "12:08", avatarText: "浦" },
        { type: "message", sender: "乙姫", text: "玉手箱にございます", isSelf: false, time: "12:08", avatarText: "乙" },
        { type: "message", sender: "浦島太郎", text: "開ければいいのか", isSelf: true, time: "12:09", avatarText: "浦" },
        { type: "message", sender: "乙姫", text: "開けてはなりません", isSelf: false, time: "12:09", avatarText: "乙" },
        { type: "message", sender: "浦島太郎", text: "そこは強く言うんだな", isSelf: true, time: "12:09", avatarText: "浦" },
        { type: "message", sender: "乙姫", text: "必ず、です", isSelf: false, time: "12:10", avatarText: "乙" },
        { type: "message", sender: "浦島太郎", text: "分かった\n開けない", isSelf: true, time: "12:10", avatarText: "浦" },
        { type: "message", sender: "亀", text: "ではお送りいたします", isSelf: false, time: "12:11", avatarText: "亀" },
        { type: "system", text: "グループ名が「村へ戻った」に変更されました" },
        { type: "message", sender: "浦島太郎", text: "着いた", isSelf: true, time: "12:16", avatarText: "浦" },
        { type: "message", sender: "浦島太郎", text: "……あれ", isSelf: true, time: "12:17", avatarText: "浦" },
        { type: "message", sender: "浦島太郎", text: "浜の様子がだいぶ違うな", isSelf: true, time: "12:17", avatarText: "浦" },
        { type: "message", sender: "浦島太郎", text: "家も見当たらん", isSelf: true, time: "12:18", avatarText: "浦" },
        { type: "message", sender: "村人", text: "どちらさまです", isSelf: false, time: "12:19", avatarText: "村" },
        { type: "message", sender: "浦島太郎", text: "浦島だが", isSelf: true, time: "12:19", avatarText: "浦" },
        { type: "message", sender: "村人", text: "浦島太郎…？", isSelf: false, time: "12:19", avatarText: "村" },
        { type: "message", sender: "浦島太郎", text: "そうだ", isSelf: true, time: "12:20", avatarText: "浦" },
        { type: "message", sender: "村人", text: "その名なら、ずいぶん昔の話で聞いたことがあります", isSelf: false, time: "12:20", avatarText: "村" },
        { type: "message", sender: "浦島太郎", text: "昔？", isSelf: true, time: "12:21", avatarText: "浦" },
        { type: "message", sender: "村人", text: "何百年も前とか", isSelf: false, time: "12:21", avatarText: "村" },
        { type: "message", sender: "浦島太郎", text: "そんな馬鹿な", isSelf: true, time: "12:22", avatarText: "浦" },
        { type: "message", sender: "浦島太郎", text: "え、ちょっと待て", isSelf: true, time: "12:22", avatarText: "浦" },
        { type: "message", sender: "浦島太郎", text: "もしかして、あの箱…", isSelf: true, time: "12:23", avatarText: "浦" },
        { type: "message", sender: "乙姫", text: "開けてはなりませんと申しました", isSelf: false, time: "12:23", avatarText: "乙" },
        { type: "message", sender: "浦島太郎", text: "今それ言うの遅いだろ", isSelf: true, time: "12:24", avatarText: "浦" },
        { type: "message", sender: "亀", text: "止めましたよ", isSelf: false, time: "12:24", avatarText: "亀" },
        { type: "message", sender: "浦島太郎", text: "まだ開けてない", isSelf: true, time: "12:24", avatarText: "浦" },
        { type: "message", sender: "乙姫", text: "ならばそのままお持ちください", isSelf: false, time: "12:25", avatarText: "乙" },
        { type: "message", sender: "浦島太郎", text: "気になりすぎる", isSelf: true, time: "12:25", avatarText: "浦" },
        { type: "message", sender: "亀", text: "おやめください", isSelf: false, time: "12:25", avatarText: "亀" },
        { type: "message", sender: "浦島太郎", text: "少しだけなら", isSelf: true, time: "12:26", avatarText: "浦" },
        { type: "message", sender: "乙姫", text: "少しでも同じです", isSelf: false, time: "12:26", avatarText: "乙" },
        { type: "message", sender: "浦島太郎", text: "……開けた", isSelf: true, time: "12:27", emphasis: true, avatarText: "浦" },
        { type: "message", sender: "亀", text: "あっ", isSelf: false, time: "12:27", avatarText: "亀" },
        { type: "message", sender: "乙姫", text: "ああ…", isSelf: false, time: "12:27", avatarText: "乙" },
        { type: "system", text: "白い煙が立ちのぼりました" },
        { type: "message", sender: "浦島太郎", text: "なんだこれ", isSelf: true, time: "12:28", avatarText: "浦" },
        { type: "message", sender: "浦島太郎", text: "急に腰がหนักい\nいや重い", isSelf: true, time: "12:28", avatarText: "浦" },
        { type: "message", sender: "亀", text: "おじいさんになっております", isSelf: false, time: "12:29", avatarText: "亀" },
        { type: "message", sender: "浦島太郎", text: "一気に来るなよ", isSelf: true, time: "12:29", avatarText: "浦" },
        { type: "message", sender: "乙姫", text: "ですから申したのに", isSelf: false, time: "12:30", avatarText: "乙" },
        { type: "message", sender: "浦島太郎", text: "そこはほんとにその通りだ", isSelf: true, time: "12:30", avatarText: "浦" }
      ]
    }
  ]
};

window.STORY_DATA = STORY_DATA;
