// `STORY_DATA` を差し替えるだけで、別作品にそのまま転用できます。
// この版では「投稿」のみを使い、各投稿の中に messages を直接並べます。

const STORY_DATA = {
  workId: "kaguyahime",
  workTitle: "かぐや姫",
  theme: {
    accentColor: "#79dd67",
    backgroundColor: "#2d2f30"
  },
  posts: [
    {
      postIndex: 1,
      groupName: "竹の中のこと",
      participants: ["翁", "媼", "かぐや姫"],
      messages: [
        { type: "system", text: "翁がグループ「竹の中のこと」を作成しました" },
        { type: "system", text: "媼がグループに参加しました" },
        { type: "message", sender: "翁", text: "今、山で竹を切っておったんだが", isSelf: false, time: "18:12", avatarText: "翁" },
        { type: "message", sender: "媼", text: "うん", isSelf: false, time: "18:12", avatarText: "媼" },
        { type: "message", sender: "翁", text: "一本だけ、妙に光る竹があってな", isSelf: false, time: "18:13", avatarText: "翁" },
        { type: "message", sender: "媼", text: "嫌な予感もするし、めでたい気もするね", isSelf: false, time: "18:13", avatarText: "媼" },
        { type: "message", sender: "翁", text: "割ってみたら", isSelf: false, time: "18:14", avatarText: "翁" },
        { type: "message", sender: "媼", text: "割ってみたら", isSelf: false, time: "18:14", avatarText: "媼" },
        { type: "message", sender: "翁", text: "中に小さな姫がおった", isSelf: false, time: "18:15", avatarText: "翁" },
        { type: "message", sender: "媼", text: "は？", isSelf: false, time: "18:15", avatarText: "媼" },
        { type: "message", sender: "翁", text: "小さい\nそれはもう、たいそう小さい", isSelf: false, time: "18:16", avatarText: "翁" },
        { type: "message", sender: "媼", text: "竹の中に？", isSelf: false, time: "18:16", avatarText: "媼" },
        { type: "message", sender: "翁", text: "入っておった", isSelf: false, time: "18:16", avatarText: "翁" },
        { type: "message", sender: "媼", text: "話が急だねえ", isSelf: false, time: "18:17", avatarText: "媼" },
        { type: "message", sender: "翁", text: "しかも光っておる", isSelf: false, time: "18:17", avatarText: "翁" },
        { type: "message", sender: "媼", text: "ますます話が急だねえ", isSelf: false, time: "18:18", avatarText: "媼" },
        { type: "system", text: "かぐや姫がグループに参加しました" },
        { type: "message", sender: "かぐや姫", text: "こんばんは", isSelf: true, time: "18:19", avatarText: "姫" },
        { type: "message", sender: "媼", text: "しゃべった", isSelf: false, time: "18:19", avatarText: "媼" },
        { type: "message", sender: "翁", text: "礼儀正しい", isSelf: false, time: "18:20", avatarText: "翁" },
        { type: "message", sender: "媼", text: "これはもう、うちで育てるしかないね", isSelf: false, time: "18:20", avatarText: "媼" },
        { type: "message", sender: "翁", text: "そう思って連れて帰ってきた", isSelf: false, time: "18:21", avatarText: "翁" },
        { type: "message", sender: "媼", text: "判断が早い", isSelf: false, time: "18:21", avatarText: "媼" },
        { type: "message", sender: "かぐや姫", text: "よろしくお願いします", isSelf: true, time: "18:22", avatarText: "姫" },
        { type: "message", sender: "媼", text: "かわいいねえ", isSelf: false, time: "18:22", avatarText: "媼" },
        { type: "message", sender: "翁", text: "しかも不思議なことに、わしが竹を切るたび黄金が出る", isSelf: false, time: "18:23", avatarText: "翁" },
        { type: "message", sender: "媼", text: "急に暮らしが安定してきたね", isSelf: false, time: "18:24", avatarText: "媼" },
        { type: "message", sender: "翁", text: "ありがたいが、何か大きな話に巻き込まれておる気もする", isSelf: false, time: "18:24", avatarText: "翁" },
        { type: "message", sender: "媼", text: "今さら気づいたのかい", isSelf: false, time: "18:25", avatarText: "媼" },
        { type: "message", sender: "かぐや姫", text: "たぶん、そうだと思います", isSelf: true, time: "18:25", avatarText: "姫" },
        { type: "message", sender: "翁", text: "姫も落ち着いておるな", isSelf: false, time: "18:26", avatarText: "翁" },
        { type: "message", sender: "媼", text: "この子、ただ者じゃないねえ", isSelf: false, time: "18:26", avatarText: "媼" }
      ]
    },
    {
      postIndex: 2,
      groupName: "求婚の者たち",
      participants: ["翁", "媼", "かぐや姫", "石作皇子", "車持皇子", "右大臣", "大納言", "中納言"],
      messages: [
        { type: "system", text: "翁がグループ「求婚の者たち」を作成しました" },
        { type: "system", text: "媼がグループに参加しました" },
        { type: "system", text: "かぐや姫がグループに参加しました" },
        { type: "message", sender: "翁", text: "姫が大きくなってからというもの", isSelf: false, time: "13:05", avatarText: "翁" },
        { type: "message", sender: "媼", text: "毎日、家の前が騒がしいねえ", isSelf: false, time: "13:05", avatarText: "媼" },
        { type: "message", sender: "翁", text: "求婚の者が多すぎる", isSelf: false, time: "13:06", avatarText: "翁" },
        { type: "message", sender: "かぐや姫", text: "多いですね", isSelf: true, time: "13:06", avatarText: "姫" },
        { type: "message", sender: "媼", text: "他人事みたいに言うねえ", isSelf: false, time: "13:07", avatarText: "媼" },
        { type: "system", text: "石作皇子がグループに参加しました" },
        { type: "system", text: "車持皇子がグループに参加しました" },
        { type: "system", text: "右大臣がグループに参加しました" },
        { type: "system", text: "大納言がグループに参加しました" },
        { type: "system", text: "中納言がグループに参加しました" },
        { type: "message", sender: "石作皇子", text: "姫、どうかこの心を", isSelf: false, time: "13:10", avatarText: "石" },
        { type: "message", sender: "車持皇子", text: "ぜひお返事を", isSelf: false, time: "13:10", avatarText: "車" },
        { type: "message", sender: "右大臣", text: "お迎えの支度はできております", isSelf: false, time: "13:11", avatarText: "右" },
        { type: "message", sender: "大納言", text: "誠心誠意お仕えします", isSelf: false, time: "13:11", avatarText: "大" },
        { type: "message", sender: "中納言", text: "わたしが最もふさわしいかと", isSelf: false, time: "13:11", avatarText: "中" },
        { type: "message", sender: "媼", text: "一気に来たねえ", isSelf: false, time: "13:12", avatarText: "媼" },
        { type: "message", sender: "翁", text: "家の前で並ぶでない", isSelf: false, time: "13:12", avatarText: "翁" },
        { type: "message", sender: "かぐや姫", text: "では、皆さまにお願いがあります", isSelf: true, time: "13:13", avatarText: "姫" },
        { type: "message", sender: "石作皇子", text: "なんなりと", isSelf: false, time: "13:13", avatarText: "石" },
        { type: "message", sender: "かぐや姫", text: "仏の御石の鉢を", isSelf: true, time: "13:14", avatarText: "姫" },
        { type: "message", sender: "石作皇子", text: "いきなり重い", isSelf: false, time: "13:14", avatarText: "石" },
        { type: "message", sender: "かぐや姫", text: "蓬莱の玉の枝を", isSelf: true, time: "13:15", avatarText: "姫" },
        { type: "message", sender: "車持皇子", text: "急に海の向こうまで来たな", isSelf: false, time: "13:15", avatarText: "車" },
        { type: "message", sender: "かぐや姫", text: "火鼠の皮衣を", isSelf: true, time: "13:16", avatarText: "姫" },
        { type: "message", sender: "右大臣", text: "燃えぬ衣ですか", isSelf: false, time: "13:16", avatarText: "右" },
        { type: "message", sender: "かぐや姫", text: "龍の首の珠を", isSelf: true, time: "13:17", avatarText: "姫" },
        { type: "message", sender: "大納言", text: "龍", isSelf: false, time: "13:17", avatarText: "大" },
        { type: "message", sender: "かぐや姫", text: "燕の子安貝を", isSelf: true, time: "13:18", avatarText: "姫" },
        { type: "message", sender: "中納言", text: "急に空へ行けと", isSelf: false, time: "13:18", avatarText: "中" },
        { type: "message", sender: "媼", text: "きれいに散らしたねえ", isSelf: false, time: "13:18", avatarText: "媼" },
        { type: "message", sender: "翁", text: "姫、本気で嫁ぐ気がないな", isSelf: false, time: "13:19", avatarText: "翁" },
        { type: "message", sender: "かぐや姫", text: "見つけてきたら考えます", isSelf: true, time: "13:19", avatarText: "姫" },
        { type: "message", sender: "石作皇子", text: "少し写しでもよろしいか", isSelf: false, time: "13:20", avatarText: "石" },
        { type: "message", sender: "かぐや姫", text: "よろしくありません", isSelf: true, time: "13:20", avatarText: "姫" },
        { type: "message", sender: "車持皇子", text: "似たものでも", isSelf: false, time: "13:20", avatarText: "車" },
        { type: "message", sender: "かぐや姫", text: "なお、よろしくありません", isSelf: true, time: "13:21", avatarText: "姫" },
        { type: "message", sender: "右大臣", text: "難題ばかりでは", isSelf: false, time: "13:21", avatarText: "右" },
        { type: "message", sender: "かぐや姫", text: "心から望むなら、取ってこられるでしょう", isSelf: true, time: "13:22", avatarText: "姫" },
        { type: "message", sender: "媼", text: "きっぱりしてるねえ", isSelf: false, time: "13:22", avatarText: "媼" },
        { type: "message", sender: "翁", text: "姫、容赦がない", isSelf: false, time: "13:22", avatarText: "翁" },
        { type: "message", sender: "かぐや姫", text: "無理なものは無理と言わずに伝えると、こうなります", isSelf: true, time: "13:23", avatarText: "姫" },
        { type: "message", sender: "媼", text: "言い方がやたらうまいねえ", isSelf: false, time: "13:23", avatarText: "媼" },
        { type: "system", text: "石作皇子がグループから退出しました" },
        { type: "system", text: "車持皇子がグループから退出しました" },
        { type: "system", text: "右大臣がグループから退出しました" },
        { type: "system", text: "大納言がグループから退出しました" },
        { type: "system", text: "中納言がグループから退出しました" },
        { type: "message", sender: "翁", text: "ずいぶん静かになったな", isSelf: false, time: "13:28", avatarText: "翁" },
        { type: "message", sender: "媼", text: "最初からこうしておけばよかったねえ", isSelf: false, time: "13:28", avatarText: "媼" }
      ]
    },
    {
      postIndex: 3,
      groupName: "月へ帰る夜",
      participants: ["翁", "媼", "かぐや姫", "帝", "月の使者"],
      messages: [
        { type: "system", text: "翁がグループ「月へ帰る夜」を作成しました" },
        { type: "system", text: "媼がグループに参加しました" },
        { type: "system", text: "かぐや姫がグループに参加しました" },
        { type: "message", sender: "翁", text: "最近、姫の様子がおかしい", isSelf: false, time: "21:03", avatarText: "翁" },
        { type: "message", sender: "媼", text: "月を見るたび、もの思いに沈んでるねえ", isSelf: false, time: "21:03", avatarText: "媼" },
        { type: "message", sender: "翁", text: "何かあるなら言いなさい", isSelf: false, time: "21:04", avatarText: "翁" },
        { type: "message", sender: "かぐや姫", text: "今まで言えませんでしたが", isSelf: true, time: "21:04", avatarText: "姫" },
        { type: "message", sender: "媼", text: "うん", isSelf: false, time: "21:05", avatarText: "媼" },
        { type: "message", sender: "かぐや姫", text: "私は、この国の者ではありません", isSelf: true, time: "21:05", avatarText: "姫" },
        { type: "message", sender: "翁", text: "そこは、まあ薄々", isSelf: false, time: "21:06", avatarText: "翁" },
        { type: "message", sender: "媼", text: "竹から来た時点で、だいぶ薄々", isSelf: false, time: "21:06", avatarText: "媼" },
        { type: "message", sender: "かぐや姫", text: "月の都の者です", isSelf: true, time: "21:07", avatarText: "姫" },
        { type: "message", sender: "翁", text: "薄々どころではなくなったな", isSelf: false, time: "21:07", avatarText: "翁" },
        { type: "message", sender: "媼", text: "話が一気に空へ行ったねえ", isSelf: false, time: "21:08", avatarText: "媼" },
        { type: "message", sender: "かぐや姫", text: "今度の満月の夜、迎えが来ます", isSelf: true, time: "21:08", avatarText: "姫" },
        { type: "message", sender: "翁", text: "困る", isSelf: false, time: "21:09", avatarText: "翁" },
        { type: "message", sender: "媼", text: "たいへん困る", isSelf: false, time: "21:09", avatarText: "媼" },
        { type: "message", sender: "かぐや姫", text: "私も帰りたくはありません", isSelf: true, time: "21:10", avatarText: "姫" },
        { type: "message", sender: "翁", text: "なら帰らずにおれぬのか", isSelf: false, time: "21:10", avatarText: "翁" },
        { type: "message", sender: "かぐや姫", text: "それができれば、そうしたいです", isSelf: true, time: "21:11", avatarText: "姫" },
        { type: "system", text: "帝がグループに参加しました" },
        { type: "message", sender: "帝", text: "話は聞いた", isSelf: false, time: "21:13", avatarText: "帝" },
        { type: "message", sender: "翁", text: "おお、帝", isSelf: false, time: "21:13", avatarText: "翁" },
        { type: "message", sender: "媼", text: "話が大きすぎるねえ", isSelf: false, time: "21:14", avatarText: "媼" },
        { type: "message", sender: "帝", text: "兵を出して守らせよう", isSelf: false, time: "21:14", avatarText: "帝" },
        { type: "message", sender: "翁", text: "頼もしい", isSelf: false, time: "21:14", avatarText: "翁" },
        { type: "message", sender: "かぐや姫", text: "お気持ちはありがたいです", isSelf: true, time: "21:15", avatarText: "姫" },
        { type: "message", sender: "帝", text: "必ず守る", isSelf: false, time: "21:15", avatarText: "帝" },
        { type: "message", sender: "かぐや姫", text: "たぶん、止められません", isSelf: true, time: "21:16", avatarText: "姫" },
        { type: "message", sender: "帝", text: "そこで弱気になるな", isSelf: false, time: "21:16", avatarText: "帝" },
        { type: "message", sender: "かぐや姫", text: "相手が月ですので", isSelf: true, time: "21:17", avatarText: "姫" },
        { type: "message", sender: "帝", text: "月か", isSelf: false, time: "21:17", avatarText: "帝" },
        { type: "message", sender: "媼", text: "相手が月だと、ちょっと話が違うねえ", isSelf: false, time: "21:18", avatarText: "媼" },
        { type: "system", text: "月の使者がグループに参加しました" },
        { type: "message", sender: "月の使者", text: "お迎えに参りました", isSelf: false, time: "21:22", avatarText: "月" },
        { type: "message", sender: "翁", text: "来たな", isSelf: false, time: "21:22", avatarText: "翁" },
        { type: "message", sender: "帝", text: "止まれ", isSelf: false, time: "21:22", avatarText: "帝" },
        { type: "message", sender: "月の使者", text: "止まりません", isSelf: false, time: "21:23", avatarText: "月" },
        { type: "message", sender: "帝", text: "きっぱりしている", isSelf: false, time: "21:23", avatarText: "帝" },
        { type: "message", sender: "かぐや姫", text: "おじいさま、おばあさま", isSelf: true, time: "21:24", avatarText: "姫" },
        { type: "message", sender: "翁", text: "行くのか", isSelf: false, time: "21:24", avatarText: "翁" },
        { type: "message", sender: "かぐや姫", text: "はい", isSelf: true, time: "21:24", avatarText: "姫" },
        { type: "message", sender: "媼", text: "せめて泣かせておくれよ", isSelf: false, time: "21:25", avatarText: "媼" },
        { type: "message", sender: "かぐや姫", text: "私もつらいです", isSelf: true, time: "21:25", avatarText: "姫" },
        { type: "message", sender: "帝", text: "せめて文を", isSelf: false, time: "21:26", avatarText: "帝" },
        { type: "message", sender: "かぐや姫", text: "置いていきます", isSelf: true, time: "21:26", avatarText: "姫" },
        { type: "message", sender: "月の使者", text: "お時間です", isSelf: false, time: "21:26", avatarText: "月" },
        { type: "message", sender: "翁", text: "時間に厳しいな", isSelf: false, time: "21:27", avatarText: "翁" },
        { type: "message", sender: "媼", text: "月はそのへん、きっちりしてるんだろうねえ", isSelf: false, time: "21:27", avatarText: "媼" },
        { type: "message", sender: "かぐや姫", text: "どうかお元気で", isSelf: true, time: "21:28", avatarText: "姫" },
        { type: "message", sender: "翁", text: "そなたもな", isSelf: false, time: "21:28", avatarText: "翁" },
        { type: "message", sender: "媼", text: "忘れるんじゃないよ", isSelf: false, time: "21:29", avatarText: "媼" },
        { type: "message", sender: "かぐや姫", text: "忘れません", isSelf: true, time: "21:29", avatarText: "姫" },
        { type: "system", text: "かぐや姫がグループから退出しました" },
        { type: "message", sender: "翁", text: "行ってしまった", isSelf: false, time: "21:31", avatarText: "翁" },
        { type: "message", sender: "媼", text: "静かになったねえ", isSelf: false, time: "21:31", avatarText: "媼" },
        { type: "message", sender: "帝", text: "月は遠いな", isSelf: false, time: "21:32", avatarText: "帝" },
        { type: "message", sender: "翁", text: "ほんとうにな", isSelf: false, time: "21:32", avatarText: "翁" }
      ]
    }
  ]
};

window.STORY_DATA = STORY_DATA;
